# Generated by Django 5.0.7 on 2024-07-24 19:48

import django.forms.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brand", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("", "Selecione ..."),
                            ("visivel", "Visível"),
                            ("invisivel", "Invisível"),
                        ],
                        default=django.forms.fields.NullBooleanField,
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
