# Generated by Django 5.0.7 on 2024-07-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brand",
            old_name="brand",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="brand",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "Selecione ..."),
                    ("Visível", "Visível"),
                    ("Invisível", "Invisível"),
                ],
                max_length=20,
            ),
        ),
    ]
