# Generated by Django 5.0.7 on 2024-07-24 18:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=200)),
                ("factory_year", models.PositiveIntegerField(max_length=4)),
                ("model_year", models.PositiveIntegerField(max_length=4)),
                ("value", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[("visivel", "Visível"), ("invisivel", "Invisível")],
                        default="Invisível",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
