# Generated by Django 5.0.7 on 2024-07-31 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0002_rename_brand_brand_name_alter_brand_status"),
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cars_value", models.FloatField(null=True)),
                ("cars_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photo_cars/"),
        ),
        migrations.AddField(
            model_name="car",
            name="plate",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car_brand",
                to="brands.brand",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="factory_year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="car",
            name="model_year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "Selecione ..."),
                    ("Visível", "Visível"),
                    ("Invisível", "Invisível"),
                ],
                max_length=20,
            ),
        ),
    ]
