# Generated by Django 5.0.7 on 2024-07-24 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0002_rename_brand_brand_name"),
        ("cars", "0003_alter_car_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car_brand",
                to="brands.brand",
            ),
        ),
    ]
