# Generated by Django 5.0.7 on 2024-07-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_alter_car_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[
                    ("", "Selecione ..."),
                    ("Visível", "Visível"),
                    ("Invisível", "Invisível"),
                ],
                max_length=10,
            ),
        ),
    ]
