# Generated by Django 5.0.7 on 2024-07-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_car_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photo_cars/"),
        ),
        migrations.AddField(
            model_name="car",
            name="plate",
            field=models.CharField(default="DEFAULT_PLATE", max_length=10),
        ),
    ]
