# Generated by Django 5.0.7 on 2024-07-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_car_photo_car_plate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="plate",
            field=models.CharField(max_length=10),
        ),
    ]
