# Generated by Django 5.0.7 on 2024-07-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_alter_car_plate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/photo_cars/"
            ),
        ),
    ]
